apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind-deployment
spec:
  selector:
    matchLabels:
      app: bitcoind
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: ghcr.io/danvau7/symmetrical-potato:latest
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 8333
        volumeMounts:
          - mountPath: /data
            name: bitcoind-data
      volumes:
        - name: bitcoind-data
          gcePersistentDisk:
            pdName: bitcoind-data
            fsType: ext4
