apiVersion: v1
kind: Service
metadata:
  name: bitcoind
spec:
  selector:
    app.kubernetes.io/name: bitcoind
  ports:
    - protocol: TCP
      port: 8333
      targetPort: 8333
  type: LoadBalancer
